//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLB_TinHoc_64131060.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DiemDanh
    {
        public int MaDiemDanh { get; set; }
        [Required(ErrorMessage ="Bạn chưa chọn nhóm")]
        public string MaNhom { get; set; }
        [Required(ErrorMessage = "Bạn chưa thành viên")]
        public string MaThanhVien { get; set; }
        [Required(ErrorMessage = "Bạn chưa thiết lập thời gian")]
        public System.DateTime NgayDiemDanh { get; set; }
        [Required(ErrorMessage = "Bạn nhập trạng thái")]
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NhomHocTap NhomHocTap { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
