//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLB_TinHoc_64131060.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ThanhVienSuKien
    {
        [Required(ErrorMessage = "Bạn chưa chọn sự kiện")]
        public string MaSuKien { get; set; }
        [Required(ErrorMessage = "Bạn chưa chọn thành viên")]
        public string MaThanhVien { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
    
        public virtual SuKien SuKien { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
